export const icons = [
  {
    originalTag: "air-conditioning",
    displayTag: "AC",
    icon: "air-conditioner-1604106/",
  },
  { originalTag: "coffee", displayTag: "coffee/tea", icon: "kettle-123921/" },
  { originalTag: "fridge", displayTag: "fridge", icon: "fridge-3194771" },
  {
    originalTag: "hairdryer",
    displayTag: "hairdryer",
    icon: "hairdryer-7260223/",
  },
  { originalTag: "heating", displayTag: "heating", icon: "heating-2228879/" },
  {
    originalTag: "high-speed-internet-access",
    displayTag: "wi-fi",
    icon: "wifi-7538046/",
  },
  { originalTag: "mini-bar", displayTag: "minibar", icon: "fridge-3194771" },
  { originalTag: "shower", displayTag: "shower", icon: "bathroom-7477580/" },
  {
    originalTag: "tea-or-coffee",
    displayTag: "coffee/tea",
    icon: "kettle-123921/",
  },
  { originalTag: "tv", displayTag: "TV", icon: "tv-4741154/" },
  { originalTag: "wi-fi", displayTag: "wi-fi", icon: "wifi-7538046/" },
  { originalTag: "wired-internet-access", displayTag: "internet", icon: "" },
  { originalTag: "with-view", displayTag: "with view", icon: "birds-4039341/" },
  { originalTag: "24 - hour gym", displayTag: "24h gym", icon: "gym-7521147/" },
  {
    originalTag: "24-hour reception",
    displayTag: "24h reception",
    icon: "reception-7009950/",
  },
  {
    originalTag: "adults only",
    displayTag: "adults only",
    icon: "dink-5750661/",
  },
  {
    originalTag: "all spaces non-smoking (public and private)",
    displayTag: "non-smoking",
    icon: "non-smoking-1485259/",
  },
  { originalTag: "bar", displayTag: "bar", icon: "bar-7505765/" },
  { originalTag: "bathtub", displayTag: "bathtub", icon: "bathroom-7477580/" },
  { originalTag: "breakfast", displayTag: "breakfast", icon: "food-3407707/" },
  {
    originalTag: "buffet breakfast",
    displayTag: "buffet breakfast",
    icon: "food-3407707/",
  },
  {
    originalTag: "business center",
    displayTag: "business center",
    icon: "business-center-2664629/",
  },
  { originalTag: "casino", displayTag: "casino", icon: "casino-7077166/" },
  {
    originalTag: "children swimming pool",
    displayTag: "kids pool",
    icon: "pool-7174266/",
  },
  {
    originalTag: "coffee/tea for guests",
    displayTag: "coffee/tea",
    icon: "kettle-123921/",
  },
  {
    originalTag: "elevator/lift",
    displayTag: "elevator",
    icon: "/elevator-7536104/",
  },
  {
    originalTag: "fitness facilities",
    displayTag: "gym",
    icon: "gym-7521147/",
  },
  { originalTag: "flat-screen TV", displayTag: "TV", icon: "tv-4741154/" },
  {
    originalTag: "free parking",
    displayTag: "free parking",
    icon: "parking-60660/",
  },
  { originalTag: "free wi-fi", displayTag: "wi-fi", icon: "wifi-7538046/" },
  { originalTag: "free internet", displayTag: "wi-fi", icon: "wifi-7538046/" },
  { originalTag: "garden", displayTag: "garden", icon: "garden-5933539/" },
  {
    originalTag: "health club",
    displayTag: "health club",
    icon: "gym-7521147/",
  },
  {
    originalTag: "heated swimming pool",
    displayTag: "heated pool",
    icon: "hot-water-9983/",
  },
  {
    originalTag: "in-room internet",
    displayTag: "in-room wi-fi",
    icon: "wifi-7538046/",
  },
  {
    originalTag: "indoor pool",
    displayTag: "indoor pool",
    icon: "pool-7183773/",
  },
  {
    originalTag: "indoor swimming pool",
    displayTag: "indoor pool",
    icon: "pool-7183773/",
  },
  { originalTag: "internet", displayTag: "wi-fi", icon: "wifi-7538046/" },
  {
    originalTag: "internet access",
    displayTag: "wi-fi",
    icon: "wifi-7538046/",
  },
  {
    originalTag: "nightclub",
    displayTag: "nightclub",
    icon: "nightclub-5448511/",
  },
  {
    originalTag: "no elevators",
    displayTag: "no elevators",
    icon: "no-elevator-958859/",
  },
  {
    originalTag: "no parking",
    displayTag: "no parking",
    icon: "no-parking-sign-1204667/",
  },
  {
    originalTag: "no pets allowed",
    displayTag: "no pets",
    icon: "no-pets-1485258/",
  },
  {
    originalTag: "outdoor heated swimming pool",
    displayTag: "swimming pool",
    icon: "pool-7183773/",
  },
  {
    originalTag: "outdoor pool",
    displayTag: "outdoor pool",
    icon: "pool-7183773/",
  },
  { originalTag: "parking", displayTag: "parking", icon: "parking-757451/" },
  {
    originalTag: "poolside bar",
    displayTag: "poolside bar",
    icon: "poolside-bar-4726392/",
  },
  {
    originalTag: "private beach",
    displayTag: "private beach",
    icon: "beach-7549958/",
  },
  {
    originalTag: "reception desk",
    displayTag: "reception",
    icon: "reception-7400565/",
  },
  {
    originalTag: "restaurant",
    displayTag: "restaurant",
    icon: "restaurant-7547134/",
  },
  {
    originalTag: "restaurant (buffet style)",
    displayTag: "buffet restaurant",
    icon: "restaurant-7547134/",
  },
  {
    originalTag: "rooftop pool",
    displayTag: "rooftop pool",
    icon: "rooftop-pool-188003/",
  },
  {
    originalTag: "room service",
    displayTag: "room service",
    icon: "room-service-7505759/",
  },
  {
    originalTag: "seasonal indoor swimming pool",
    displayTag: "indoor pool",
    icon: "pool-7183773/",
  },
  {
    originalTag: "seasonal outdoor swimming pool",
    displayTag: "outdoor pool",
    icon: "pool-7183773/",
  },
  {
    originalTag: "smoke-free property",
    displayTag: "smoke-free",
    icon: "non-smoking-1485259/",
  },
  {
    originalTag: "smoking allowed",
    displayTag: "smoking allowed",
    icon: "smoking-7235325/",
  },
  {
    originalTag: "smoking allowed in bedrooms",
    displayTag: "smoking allowed",
    icon: "smoking-7235325/",
  },
  {
    originalTag: "smoking areas",
    displayTag: "smoking areas",
    icon: "smoking-7235325/",
  },
  {
    originalTag: "snack bar",
    displayTag: "snack bar",
    icon: "coffee-shop-3147856/",
  },
  {
    originalTag: "swimming pool",
    displayTag: "swimming pool",
    icon: "pool-7183773/",
  },
  { originalTag: "terrace", displayTag: "terrace", icon: "terrace-7477538/" },
  {
    originalTag: "wi-fi in the hotel",
    displayTag: "wi-fi",
    icon: "wifi-7538046/",
  },
];
