import { NextRequest, NextResponse } from "next/server";
import { getFeedItems } from "@/lib/feed/feedData";
import { toXml } from "@/lib/feed/metaCatalog";

/**
 * Meta (Facebook) product-catalog feed. Three fixes were tried and each
 * verified live to make NO difference: setting Content-Encoding: gzip on
 * the origin response, Cache-Control: no-transform, and serving via ISR
 * instead of force-dynamic. In every case Vercel's edge force-compressed
 * the response with Brotli whenever the client's Accept-Encoding included
 * "br" — Meta's fetcher advertises br support but apparently doesn't
 * actually decode it, so it always received undecodable binary and
 * rejected the feed as "file format isn't supported".
 *
 * The only thing that reliably avoids Vercel's forced Brotli (verified
 * live) is the CLIENT explicitly sending Accept-Encoding: identity — not
 * something Meta's fetcher can be made to do. So the actual XML is instead
 * generated by a backoffice cron (`publishMetaFeed`, every 30 min) that
 * fetches THIS route with `?source=1` + Accept-Encoding: identity and
 * republishes the plain bytes as a static file in Supabase Storage — a
 * different host/CDN entirely, no Vercel edge in the path. Without the
 * param this route just redirects there, so the branded mega-events.co.il
 * URL stays the one registered with Meta while delivery bypasses the
 * problem completely.
 *
 * `?source=1` MUST keep serving a live build (not a redirect): when this
 * route was redirect-only (2026-07-20 → 22) the cron followed its own 307,
 * republished the previous snapshot forever, and the feed silently froze.
 * The cron now rejects redirects and requires the X-Feed-Generated header
 * as a guard against reintroducing that loop.
 */
export const dynamic = "force-dynamic";
export const maxDuration = 60;

// "-feed" suffix deliberately avoids "feeds/meta-catalog.xml" — that path
// got Cloudflare-cache-poisoned during testing (identical content → same
// weak etag every run → Cloudflare kept serving a stale cached response
// from before the octet-stream fix, regardless of TTL or re-uploads).
const STORAGE_FEED_URL =
  "https://fandqafngybfdyslofmr.supabase.co/storage/v1/object/public/public_resources/feeds/meta-catalog-feed.xml";

export async function GET(request: NextRequest) {
  if (request.nextUrl.searchParams.get("source") !== "1") {
    return NextResponse.redirect(STORAGE_FEED_URL, 307);
  }

  try {
    const generatedAt = new Date().toISOString();
    const { items } = await getFeedItems();
    return new NextResponse(toXml(items, generatedAt), {
      status: 200,
      headers: {
        "Content-Type": "text/xml; charset=utf-8",
        "X-Feed-Generated": generatedAt,
        "Cache-Control": "no-store",
      },
    });
  } catch (e) {
    console.error("[feed] meta-catalog.xml live build failed:", e);
    return new NextResponse("feed generation failed", { status: 500 });
  }
}
