import { NextResponse } from "next/server";

/**
 * Meta (Facebook) product-catalog feed. Three fixes were tried and each
 * verified live to make NO difference: setting Content-Encoding: gzip on
 * the origin response, Cache-Control: no-transform, and serving via ISR
 * instead of force-dynamic. In every case Vercel's edge force-compressed
 * the response with Brotli whenever the client's Accept-Encoding included
 * "br" — Meta's fetcher advertises br support but apparently doesn't
 * actually decode it, so it always received undecodable binary and
 * rejected the feed as "file format isn't supported".
 *
 * The only thing that reliably avoids Vercel's forced Brotli (verified
 * live) is the CLIENT explicitly sending Accept-Encoding: identity — not
 * something Meta's fetcher can be made to do. So the actual XML is instead
 * generated by a backoffice cron (`publishMetaFeed`, every 15 min) that
 * fetches this app's own feed data with Accept-Encoding: identity and
 * republishes the plain bytes as a static file in Supabase Storage — a
 * different host/CDN entirely, no Vercel edge in the path. This route just
 * redirects there, so the branded mega-events.co.il URL stays the one
 * registered with Meta while delivery bypasses the problem completely.
 */
// "-feed" suffix deliberately avoids "feeds/meta-catalog.xml" — that path
// got Cloudflare-cache-poisoned during testing (identical content → same
// weak etag every run → Cloudflare kept serving a stale cached response
// from before the octet-stream fix, regardless of TTL or re-uploads).
const STORAGE_FEED_URL =
  "https://fandqafngybfdyslofmr.supabase.co/storage/v1/object/public/public_resources/feeds/meta-catalog-feed.xml";

export async function GET() {
  return NextResponse.redirect(STORAGE_FEED_URL, 307);
}
